table cotacoes
	lineageTag: 16f41f07-be4d-4a1d-8268-954b81411e90
	sourceLineageTag: b1b76725-563a-4ec5-a546-77368411c1d8

	measure 'Cotação do dia 2' = EXTERNALMEASURE("Cotação do dia", DOUBLE, "DirectQuery para AS – demo_git_direct_lake")
		displayFolder: Medidas
		lineageTag: ce05f604-4ceb-4dc7-85b0-6d2b8e7421fa
		sourceLineageTag: 0191516f-3026-4f4c-8dd3-f28102156ee4
		dataCategory: Uncategorized

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			```
		displayFolder: Medidas
		lineageTag: 68c35fdf-db27-413d-a333-9bce5059970f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação do dia' = AVERAGE(cotacoes[Cotacao])
		displayFolder: Medidas
		lineageTag: e0dca70c-4e21-47fd-b6ac-496a1b68e394

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moeda,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		displayFolder: Medidas
		lineageTag: 7c896566-f050-4b92-a4d3-e56daf2fb136

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 6b8fc6a8-656c-46cf-9504-52434a7b5c35
		sourceLineageTag: 910632fc-e070-435d-93c7-23f2a5780993
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = User

	column DataHoraCotacao
		dataType: dateTime
		formatString: General Number
		displayFolder: Colunas
		lineageTag: b5a90ccc-6b96-427a-acd0-86a51995d9e7
		sourceLineageTag: a1b08521-0acf-4dde-8dd7-86f4ddec359c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: DataHoraCotacao

		annotation SummarizationSetBy = User

	column DataCotacao
		dataType: dateTime
		formatString: General Number
		displayFolder: Colunas
		lineageTag: f3541721-169f-4546-a64e-f6eec5935216
		sourceLineageTag: 68177a87-b6dd-4834-b940-bcfa8ba0fa1e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: DataCotacao

		annotation SummarizationSetBy = User

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: 4b8b40e8-2d92-4856-92a3-e2d3710c2a99
		sourceLineageTag: 3cd2439c-5002-43b4-b81f-3856c8dc73e7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Cotacao

		annotation SummarizationSetBy = User

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: 5c9ec238-a901-4c27-ac9c-b804545191f6
		sourceLineageTag: 0a15520c-0b06-4c8c-8905-07803d705661
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: TipoBoletim

		annotation SummarizationSetBy = User

	partition cotacoes = entity
		mode: directQuery
		source
			entityName: cotacoes
			expressionSource: 'DirectQuery para AS – demo_git_direct_lake'

