table transacoes
	lineageTag: e1479316-404a-47f7-ade7-0a983d9fe664
	sourceLineageTag: b3f1cca2-0c19-4196-b7de-39cdc245ed3b

	measure Transacoes = EXTERNALMEASURE("Transacoes", DOUBLE, "DirectQuery para AS – demo_git_direct_lake")
		displayFolder: Medidas
		lineageTag: 08616a06-6730-43fe-802f-01a26259739e
		sourceLineageTag: 17dc23a0-bb16-4fba-9252-653eccbccfcb
		dataCategory: Uncategorized

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: 05f44967-7101-4170-a244-7a43ec1d94a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		displayFolder: Colunas
		lineageTag: 8c58bd3d-2360-416e-a4fc-f94ebc6d6341
		sourceLineageTag: c4900332-e87f-47aa-9511-b625057fd56a
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = User

	column Data
		dataType: dateTime
		formatString: General Number
		displayFolder: Colunas
		lineageTag: 1066d4f4-3acd-4571-92dd-451c4f846893
		sourceLineageTag: 46676c8e-53b0-4856-8634-7cd870467215
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = User

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: abe6e230-f532-4dbe-a6f9-457bccf4d518
		sourceLineageTag: 5847787a-d9f8-47d8-b455-ca744093673c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = User

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: ba49457d-0a32-4f78-a790-5d5ddfd885da
		sourceLineageTag: 2d41064b-03f9-46ce-9965-c792020fe39a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = User

	partition transacoes = entity
		mode: directQuery
		source
			entityName: transacoes
			expressionSource: 'DirectQuery para AS – demo_git_direct_lake'

