table cotacoes
	lineageTag: 9cd6ed58-95e7-4bac-be69-6a280b5cd499
	sourceLineageTag: [dbo].[cotacoes]

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			```
		displayFolder: Medidas
		lineageTag: ace1378b-b969-4cb1-af6d-fff8eb4b0042

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Cotação do dia' = AVERAGE(cotacoes[Cotacao])
		displayFolder: Medidas
		lineageTag: 2a706123-ff81-4685-891f-06c15cf3f4f0

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		displayFolder: Medidas
		lineageTag: abdfd985-cd40-4324-bdfd-bb1f9e6b1ee3

		changedProperty = Name

		changedProperty = DisplayFolder

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: e91fa17b-9d96-484f-a4e5-a439eb31c98f
		sourceLineageTag: Moeda
		summarizeBy: none
		sourceColumn: Moeda

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column DataHoraCotacao
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: 39820a4f-300d-4b6b-a71f-5058ad10e8e2
		sourceLineageTag: DataHoraCotacao
		summarizeBy: none
		sourceColumn: DataHoraCotacao

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column DataCotacao
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: 6d3906bd-5b1d-4e18-8eee-51b19ae6e106
		sourceLineageTag: DataCotacao
		summarizeBy: none
		sourceColumn: DataCotacao

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: cc883601-1659-46b6-bed9-d53f0c200ed3
		sourceLineageTag: Cotacao
		summarizeBy: sum
		sourceColumn: Cotacao

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: 86fb34bc-4d70-47ea-ba12-715f77142dcc
		sourceLineageTag: TipoBoletim
		summarizeBy: none
		sourceColumn: TipoBoletim

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	partition cotacoes = entity
		mode: directLake
		source
			entityName: cotacoes
			expressionSource: 'DirectLake - lake'

