table transacoes
	lineageTag: 204b99a7-bd0f-4789-858b-33b9b527048a
	sourceLineageTag: [dbo].[transacoes]

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: dc05865c-4615-47ca-a075-59b65023b565

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: int64
		formatString: 0
		displayFolder: Colunas
		lineageTag: c73a5f42-6f65-4b5b-b227-752c1e1d1a93
		sourceLineageTag: ID
		summarizeBy: count
		sourceColumn: ID

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: d7ff6ed5-332b-44d9-97d0-f8834ad76fd1
		sourceLineageTag: Data
		summarizeBy: none
		sourceColumn: Data

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: 7a74ae0b-2db6-4d40-8efa-ca0628b8fe41
		sourceLineageTag: Total
		summarizeBy: sum
		sourceColumn: Total

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 505a8156-db4d-433f-bfe3-5991308936f8
		sourceLineageTag: Moeda
		summarizeBy: none
		sourceColumn: Moeda

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	partition transacoes = entity
		mode: directLake
		source
			entityName: transacoes
			expressionSource: 'DirectLake - lake'

